FROM python:3.9

WORKDIR /usr/src/app

COPY ./app_listen/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

VOLUME /dockerfilevolume
COPY ./app_listen /usr/src/app
CMD ["listen.py"]
ENTRYPOINT ["python3"]